In [63]:
filepath = 'Day08Input.txt'

# Problem 1

In [64]:
import numpy as np

def load_input(filepath):
    with open(filepath) as f:
        lines = f.readlines()
        height = len(lines)
        weight = len(lines[0].strip())
        
        grid = np.zeros((height, weight), dtype=np.uint8)
        for row, line in enumerate(lines):
            for col, char in enumerate(line.strip()):
                grid[row][col] = int(char)
        
        return grid

In [65]:
grid = load_input(filepath)
print(grid)

[[3 0 1 ... 1 2 3]
 [2 1 2 ... 1 1 1]
 [2 0 1 ... 2 3 1]
 ...
 [0 1 2 ... 2 0 3]
 [1 3 2 ... 1 1 2]
 [0 1 1 ... 3 0 2]]


In [66]:
import itertools

visible_mask = np.zeros_like(grid, dtype=bool)

for row, col in itertools.product(range(len(grid)), range(len(grid[0]))):
    height = grid[row][col]
    
    # Edges are always visible
    if row == 0 or row == len(grid) - 1 or col == 0 or col == len(grid[0]) - 1:
        visible_mask[row][col] = True
    
    elif np.max(grid[:row, col]) < height or np.max(grid[row + 1:, col]) < height or np.max(grid[row, :col]) < height or np.max(grid[row, col + 1:]) < height:
        visible_mask[row][col] = True
print(np.sum(visible_mask))

1672


# Problem 2

In [67]:
scores = np.ones(grid.shape, dtype=np.uint32)

for row, col in itertools.product(range(len(grid)), range(len(grid[0]))):
    height = grid[row][col]
    
    if row == 0 or row == len(grid) - 1 or col == 0 or col == len(grid[0]) - 1:
        scores[row][col] = 0

    # Check up
    if row > 0:
        for score, i in enumerate(range(row - 1, -1, -1), start=1):
            if grid[i][col] >= height or i == 0:
                scores[row][col] *= score
                break

    # Check down
    if row < len(grid) - 1:
        for score, i in enumerate(range(row + 1, len(grid)), start=1):
            if grid[i][col] >= height or i == len(grid) - 1:
                scores[row][col] *= score
                break
    
    # Check left
    if col > 0:
        for score, i in enumerate(range(col - 1, -1, -1), start=1):
            if grid[row][i] >= height or i == 0:
                scores[row][col] *= score
                break
    
    # Check right
    if col < len(grid[0]) - 1:
        for score, i in enumerate(range(col + 1, len(grid[0])), start=1):
            if grid[row][i] >= height or i == len(grid[0]) - 1:
                scores[row][col] *= score
                break

print(np.max(scores))

327180
